### ISSUE TITLE
Внешний вид

### ISSUE THREAD

**Issue by AbdulkodirBurganov** [Arlincourt/fsd#1]
У слайдера слиплись все фотографии
![баг со слайдером](https://user-images.githubusercontent.com/89448992/145672205-1651b968-b6c3-47a7-b48d-3c7dd874792f.gif)

**Comment by AbdulkodirBurganov** [comment]
Тут похоже чутка цвета напутал
![изображение](https://user-images.githubusercontent.com/89448992/145672330-9263ccf7-b48a-4f6e-986d-3fb6ba9cee40.png)

**Comment by AbdulkodirBurganov** [comment]
На всех интерактивных элементах нужен cursor: pointer
![range-slider](https://user-images.githubusercontent.com/89448992/145675347-523330de-ec65-43f3-8b9c-a9dea84eda7d.gif)

**Comment by AbdulkodirBurganov** [comment]
С цветами pie-chart остался баг

**Comment by AbdulkodirBurganov** [comment]
Вот тут вот слипаются элементы при размере страницы в 360px и меньше
![изображение](https://user-images.githubusercontent.com/89448992/147158931-fde8e533-8218-4a5f-8b1f-119f0c48ba70.png)
![изображение](https://user-images.githubusercontent.com/89448992/147159014-55138691-213b-4146-94c9-8bad1567b641.png)

**Comment by AbdulkodirBurganov** [comment]
Вот здесь не тот шрифт
![изображение](https://user-images.githubusercontent.com/89448992/147159641-01ed0c47-0348-43a8-9430-ba6ffedef41c.png)
И в других дропдаунах тоже проверь

**Comment by AbdulkodirBurganov** [comment]
Вот тут тоже слипаются
![изображение](https://user-images.githubusercontent.com/89448992/147159871-8bec5cc8-b7c7-4bf0-8ba0-50bca9bdb372.png)

**Comment by AbdulkodirBurganov** [comment]
На кнопках вроде как тоже шрифты не совпадают
![изображение](https://user-images.githubusercontent.com/89448992/147160717-7176811f-d729-4838-92a0-55dc085623c1.png)

**Comment by AbdulkodirBurganov** [comment]
Было бы неплохо, если бы пагинация выравнивалась по центру относительно карточек номеров
![изображение](https://user-images.githubusercontent.com/89448992/147218499-c82f8c21-fb84-4161-826e-6fd0cdf72dae.png)

**Comment by AbdulkodirBurganov** [comment]
Rich checkbox поехал
![изображение](https://user-images.githubusercontent.com/89448992/147218875-4177772b-4fe3-44ce-9783-46bfb2f84448.png)

**Comment by AbdulkodirBurganov** [comment]
Немного странно выглядит, что все по центру, кроме доступности)
![изображение](https://user-images.githubusercontent.com/89448992/147219210-70c9603e-67f1-4d47-bf1c-28924acfb017.png)

**Comment by AbdulkodirBurganov** [comment]
Странноватый выступ у dropdown
![изображение](https://user-images.githubusercontent.com/89448992/147219530-340c760b-18b3-4b51-9c60-3847cb08c4d9.png)

**Comment by AbdulkodirBurganov** [comment]
Здесь еще осталось
![изображение](https://user-images.githubusercontent.com/89448992/147470366-539ed7ed-7101-4809-b87e-3708c832387f.png)

**Comment by AbdulkodirBurganov** [comment]
Здесь все-таки letter-spacing лишний
![letter-spacing](https://user-images.githubusercontent.com/89448992/147470694-69488c2e-240a-4abe-adaa-b8789585160f.gif)

**Comment by AbdulkodirBurganov** [comment]
Отступ остался
![изображение](https://user-images.githubusercontent.com/89448992/147470840-9a9924ad-3a93-444f-af67-f8fb9df8b18a.png)

**Comment by AbdulkodirBurganov** [comment]
Оступов нет
![изображение](https://user-images.githubusercontent.com/89448992/147471062-7c971f94-a941-4328-ab6b-b0722f92fcc4.png)

**Comment by AbdulkodirBurganov** [comment]
Между токсином и меню нет отступа
![изображение](https://user-images.githubusercontent.com/89448992/147471358-b9899c33-6b54-4e42-bf78-c68aab0bbed1.png)

**Comment by AbdulkodirBurganov** [comment]
Текст на стрелку наезжает
![изображение](https://user-images.githubusercontent.com/89448992/147471280-afd265fa-b77a-453e-944d-6bc427a6409f.png)

**Comment by AbdulkodirBurganov** [comment]
> Здесь еще осталось ![изображение](https://user-images.githubusercontent.com/89448992/147470366-539ed7ed-7101-4809-b87e-3708c832387f.png)

Вот это при ширине в 380 пикселей еще осталось

**Comment by AbdulkodirBurganov** [comment]
Вот в такие места можно поставить user-select: none, чтобы так не выделялось при нажатии.
![user-select](https://user-images.githubusercontent.com/89448992/152019312-d77f3499-e850-4f49-b833-1e072901128e.gif)

**Comment by Arlincourt** [comment]
17d07f7ef4bd1b490946e68f0889898dbc5b0948 ID коммита, где исправлено user-select: none
