### ISSUE TITLE
Pug

### ISSUE THREAD

**Issue by AbdulkodirBurganov** [Arlincourt/fsd#7]
Вот по этому [пункту](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#2.5) надо дополнить
![image](https://user-images.githubusercontent.com/89448992/150654276-eb4fd6d2-1ff7-4541-8682-c02bbeb0cbe0.png)

**Comment by NaincyKumariKnoldus** [comment]
Hey @AbdulkodirBurganov Can I solve this?

**Comment by AbdulkodirBurganov** [comment]
Sorry, but this is a code review that relates to an internship, so it should be corrected by the author of the code.

> Hey @AbdulkodirBurganov Can I solve this?

**Comment by AbdulkodirBurganov** [comment]
Вот здесь лучше использовать деструктуризацию согласно этому [пункту](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#1.6). В целом к js-подобному коду в pug применяются требования и best practices по js.

![image](https://user-images.githubusercontent.com/89448992/150697796-5ad8306b-fcc7-420d-8928-97d6cb936520.png)

**Comment by NaincyKumariKnoldus** [comment]
okay @AbdulkodirBurganov no problem.

**Comment by AbdulkodirBurganov** [comment]
![image](https://user-images.githubusercontent.com/89448992/151706569-ace2648d-674d-41cb-ba50-b4a564f10317.png)
Вот здесь насчет класса с js. По сути по нашим стандартам класс должен дублироваться и к нему добавляться приставка js-. То есть js-accordeon__icon.

**Comment by AbdulkodirBurganov** [comment]
![image](https://user-images.githubusercontent.com/89448992/151706774-c1208dea-3ea2-4c53-a5e7-944efa86f124.png)
Мне кажется, что здесь accordeon__title лишний. Обычно блоки оборачивают в отдельные дивы, чтобы задать им внешнюю позиционирование относительно других элементов, а тут никаких стилей не навешано на этот элемент.

**Comment by AbdulkodirBurganov** [comment]
1. В js-подобном коде даже в pug применяются те правила форматирования, которые действуют и на обычный js. В данном случае я имею в виду отступы от фигурных скобок. К сожалению, линтер не проверяет js-файлы и такие вещи приходится вручную исправлять. 
![image](https://user-images.githubusercontent.com/89448992/153733615-04d21421-9bb3-48ba-a294-9653232b9216.png)
2. Вот здесь вот не совсем по БЭМ. Я имею в виду icon-expand_more.
![image](https://user-images.githubusercontent.com/89448992/153733668-a3c05a0b-1dcf-434a-a135-1c32edf34d81.png)
3. Вот тут лучше использовать null, вместо undefined. Можешь почитать, когда использовать null, а когда undefined. К тому же undefined задается по умолчанию аргументу, если ничего не передали, то есть от этого присвоения по сути ничего не меняется.
![image](https://user-images.githubusercontent.com/89448992/153734175-7db61516-1bc4-4f1b-9528-d6323ec3e9db.png)
4. Вот тут вместо div можно просто точку поставить, как ты в остальных случаях делал. Точка как раз создает div. 
![image](https://user-images.githubusercontent.com/89448992/153734200-c19b782c-920f-4665-9f2a-25b160718f2d.png)

**Comment by AbdulkodirBurganov** [comment]
Вот тут вот у тебя в корне блока почему-то элемент лежит
![image](https://user-images.githubusercontent.com/89448992/155128155-9f3db35e-f384-4e4a-9562-41f031833fd1.png)
